In [2]:
import numpy as np

1. Найти индексы ненулевых элементов в заданном массиве

In [81]:
arr = np.random.randint(0,4+1,size=20)
print(arr)
result = np.nonzero(arr)
print(result)

[0 3 4 0 4 3 2 3 4 1 4 2 0 3 2 4 2 1 1 0]
(array([ 1,  2,  4,  5,  6,  7,  8,  9, 10, 11, 13, 14, 15, 16, 17, 18],
      dtype=int64),)


2. Создать nxn единичную матрицу

In [4]:
n = np.random.randint(2,5+1)
print(n)
matrix = np.identity(n,dtype='int64')
print(matrix)

4
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


3. Создать массив nxnxn со случайными значениями

In [5]:
n = np.random.randint(1,4+1)
print(n)
arr = np.random.randint(-10,10+1,size=(n, n, n))
print(arr)

3
[[[ -8   4  -4]
  [ -9   2  -4]
  [ -4   6  -3]]

 [[ -5   2  -2]
  [ 10   3  -6]
  [  3   5   8]]

 [[ -6  -4   5]
  [-10  -9   8]
  [  5   8  -9]]]


4. Создать вектор (одномерный массив) размера n, заполненный нулями

In [29]:
n = np.random.randint(2, 10+1)
print(n)
vector = np.zeros((n), dtype='int64')
print(vector)

8
[0 0 0 0 0 0 0 0]


5. Создать вектор размера 1n, заполненный нулями, но пятый элемент равен 1

In [87]:
n = np.random.randint(5, 10+1)
print(n)
vector = np.zeros((1,n), dtype='int64')
vector[0,4] = 1
print(vector)

8
[[0 0 0 0 1 0 0 0]]


6. Создать вектор со значениями от n до m

In [44]:
n = int(input())
m = int(input())
vector = np.arange(n,m+1,dtype='int64')
print(vector)

[2 3 4 5 6 7 8]


7. Развернуть одномерный массив (первый становится последним)

In [62]:
arr = np.random.randint(10,size=5)
print(arr)
arr = np.flip(arr)
print(arr)

[9 4 1 5 8]
[8 5 1 4 9]


8. Создать матрицу с 0 внутри, и 1 на границах

In [65]:
n = np.random.randint(2,5+1)
m = np.random.randint(2,5+1)
print(n,m)
matrix = np.ones((n,m),dtype='int64')
print(matrix)
print()
if (n != 2) and (m != 2):
    matrix[1:-1, 1:-1] = 0
    print(matrix)


4 4
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]

[[1 1 1 1]
 [1 0 0 1]
 [1 0 0 1]
 [1 1 1 1]]


9. Создать nxn матрицу с 1,2,..,n-1 под диагональю

In [56]:
n = np.random.randint(2,10+1)
print(n)
matrix = np.arange(1,n+1,dtype='int64')  * np.eye(n,k=-1,dtype='int64') 
print(matrix)

6
[[0 0 0 0 0 0]
 [1 0 0 0 0 0]
 [0 2 0 0 0 0]
 [0 0 3 0 0 0]
 [0 0 0 4 0 0]
 [0 0 0 0 5 0]]


10. Создать nxn матрицу и заполнить её в шахматном порядке

In [76]:
n = np.random.randint(2, 8+1)
print(n)
matrix = np.zeros((n,n), dtype='int64')
matrix[::2,::2] = 1
matrix[1::2,1::2] = 1
print(matrix)

8
[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


11. Заменить максимальный элемент на ноль


In [177]:
arr = np.random.randint(-10,10+1,size= np.random.randint(2,10+1))
print(arr)
index_max = np.argwhere(arr == np.amax(arr))
print(index_max)
arr[index_max]=0
print(arr)

[-1 10 -6 10  9 -6  0 -6]
[[1]
 [3]]
[-1  0 -6  0  9 -6  0 -6]


12. Найти ближайшее к заданному значению число в заданном массиве

In [191]:
value = np.random.randint(-10,10+1)
print(value)
arr = np.random.randint(-10,10+1,size= np.random.randint(2,10+1))
print(arr)
index_abs = np.abs(arr - value)
print(index_abs)
index_min = np.argwhere(index_abs == np.amin(index_abs))
print(index_min)

6
[ 8  4 -2  7  6  2  4]
[2 2 8 1 0 4 2]
[[4]]


13. Дан четырехмерный массив, посчитать сумму по последним двум осям

In [208]:
arr = np.random.randint(0, 10, size=(2, 3, 4, 5))
print(arr)
result = np.sum(arr,axis=(-2,-1))
print(result)

[[[[0 0 4 4 9]
   [3 4 5 7 7]
   [8 7 7 4 3]
   [9 9 5 5 8]]

  [[1 0 7 6 2]
   [2 6 3 5 9]
   [6 9 0 9 3]
   [7 4 5 2 2]]

  [[4 7 2 5 1]
   [8 8 6 5 9]
   [0 8 0 3 8]
   [1 8 2 2 5]]]


 [[[3 8 7 0 9]
   [6 7 5 4 3]
   [0 5 4 8 5]
   [0 7 4 9 5]]

  [[9 8 3 4 7]
   [0 9 3 6 8]
   [4 8 4 3 8]
   [7 3 2 5 3]]

  [[4 1 2 0 5]
   [4 1 8 7 2]
   [2 1 6 9 0]
   [7 9 5 5 7]]]]
[[108  88  92]
 [ 99 104  85]]


14. Определить, есть ли в 2D массиве нулевые столбцы

In [214]:
arr = np.array([[1, 0, 3],
                [4, 0, 6],
                [7, 0, 9]])

result = np.all(arr == 0, axis=0)

print(result)

[False  True False]


15. Отнять среднее из каждой строки в матрице

In [261]:
n = np.random.randint(2,5+1)
m = np.random.randint(2,5+1)
print(n,m)
matrix = np.random.randint(0, 10, size=(n,m))
print(matrix)
result = np.mean(matrix, axis=1, keepdims=True)
print(result)
print(matrix - result)

5 5
[[5 7 5 3 0]
 [4 6 0 5 0]
 [0 3 1 6 0]
 [1 0 5 1 0]
 [5 5 3 2 5]]
[[4. ]
 [3. ]
 [2. ]
 [1.4]
 [4. ]]
[[ 1.   3.   1.  -1.  -4. ]
 [ 1.   3.  -3.   2.  -3. ]
 [-2.   1.  -1.   4.  -2. ]
 [-0.4 -1.4  3.6 -0.4 -1.4]
 [ 1.   1.  -1.  -2.   1. ]]
